---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/main/schema/compose-spec.json
services:
  nginx:
    image: nginx
    container_name: nginx-ghost
    restart: always
    ports:
      - "58080:58080"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - ghost
    networks:
      - ghost_network

  ghost:
    image: eallion/ghost:latest
    container_name: ghost
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      url: https://ghost.eallion.com
      labs__publicAPI: true
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${DATABASE_USER:-ghost}
      database__connection__password: ${DATABASE_PASSWORD:?DATABASE_PASSWORD environment variable is required}
      database__connection__database: ghost
      storage__active: ghost-cos
      storage__ghost-cos__SecretId: ${COS_SECRET_ID}
      storage__ghost-cos__SecretKey: ${COS_SECRET_KEY}
      storage__ghost-cos__Bucket: ${COS_BUCKET}
      storage__ghost-cos__Region: ${COS_REGION}
      storage__ghost-cos__baseUrl: ${CDN_URL:-}
      storage__ghost-cos__basePath: /ghost/content/images/
      storage__ghost-cos__rename: false
      storage__ghost-cos__forcePathStyle: false
    volumes:
      - ${UPLOAD_LOCATION:-./data/ghost}:/var/lib/ghost/content
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ghost_network
    deploy:
      resources:
        limits:
          memory: 256M

  db:
    image: mysql:8.0
    container_name: mysql-ghost
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:?DATABASE_ROOT_PASSWORD environment variable is required}
      MYSQL_USER: ${DATABASE_USER:-ghost}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD environment variable is required}
      MYSQL_DATABASE: ghost
    volumes:
      - ${MYSQL_DATA_LOCATION:-./data/mysql}:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -p$$MYSQL_ROOT_PASSWORD -h 127.0.0.1
      interval: 1s
      start_period: 30s
      start_interval: 10s
      retries: 120
    networks:
      - ghost_network
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  ghost_network:
