main:
  push:
    - name: hugo-build-deploy-edgeone-pages
      runner:
        cpus: 8
      imports: https://cnb.cool/eallion/env/-/blob/main/eallion.com/envs.yml
      stages:
        - name: build-hugo
          image: hugomods/hugo:base-0.148.0
          commands:
            - hugo --minify
        - name: deploy-to-edgeone
          image: tencentcom/deploy-eopages:latest
          script: |
            edgeone pages deploy ./public -n hugo-blog -t $EDGEONE_PAGES_API_TOKEN
