main:
  push:
    - name: hugo-build-deploy-edgeone
      runner:
        cpus: 8
      imports: https://cnb.cool/eallion/env/-/blob/main/eallion.com/envs.yml
      stages:
        - name: build-hugo
          image: hugomods/hugo:base-0.150.0
          timeout: 10m
          commands:
            - hugo --minify
        - name: deploy-to-cos
          image: tencentcom/coscli
          timeout: 2h
          volumes:
            - /root/cos-snapshot-path
          commands: |
            coscli config set --secret_id $COS_SECRET_ID --secret_key $COS_SECRET_KEY
            coscli config add --init-skip=true -b $COS_BUCKET -r $COS_REGION
            coscli sync ./public/ cos://$COS_BUCKET -r --snapshot-path=/root/cos-snapshot-path
        - name: purge-edgeone
          image: docker.cnb.cool/znb/cdn-refresh
          timeout: 10m
          settings:
            kind: "tencenteo"
            ak: "${COS_SECRET_ID}"
            sk: "${COS_SECRET_KEY}"
            rtype: "path"
            domain: "eallion.com"
            urls:
              - "https://www.eallion.com/"
        # - name: deploy-to-oss
        #   env:
        #     ACCESS_KEY_ID: $ACCESS_KEY_ID
        #     ACCESS_KEY_SECRET: $ACCESS_KEY_SECRET
        #     BUCKET: eallion-com
        #     ENDPOINT: oss-cn-shanghai.aliyuncs.com
        #     FOLDER: public
        #     CNAME: false
        #     SKIP_SETTING: true
        #     INCREMENTAL: true
        #   image: fangbinwei/aliyun-oss-website-action:v1
        #   timeout: 2h
        #   script: aliyun-oss-website-action
